name: version_up
on:
  create
jobs:
  version:
    if: startsWith(github.ref, 'refs/heads/release-')
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      uses: mdecoleman/pr-branch-name@1.0.0
      id: extract_branch
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract version
      shell: bash
      run: |
        branch=${{ steps.extract_branch.outputs.branch }}
        echo "##[set-output name=version;]$(echo ${branch#release-})"
      id: extract_version
    - uses: yanamura/ios-bump-version@version-file
      with:
        version: ${{ steps.extract_version.outputs.version }}
    - name: run
      run: |
        echo ${{ steps.extract_branch.outputs.branch }}
        git diff
        git config --global user.name "yanamura"
        git config --global user.email "yanamura3@gmail.com"
        git fetch -p
        git checkout ${{ steps.extract_branch.outputs.branch }}
        git add .
        git commit -m ":punch: bump version"
        git push origin ${{ steps.extract_branch.outputs.branch }}
        