name: automerge
on:
  pull_request_review_comment:
    types: [created]
jobs:
  automerge:
    if: contains(github.event.comment.body, '#merge')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: mdecoleman/pr-branch-name@1.0.0
        id: vars
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.vars.outputs.branch }}
      - name: merge pull request
        run: ./merge.sh ${{ steps.vars.outputs.branch }}
