name: add hash to title
on:
  pull_request:
    types:
      - opened
jobs:
  title_hash:
    runs-on: ubuntu-latest
    steps:
    - name: add hash to title
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            title: `#${context.issue.number} ${context.payload.pull_request.title}`
          })          
